#*=====================================================================*/
#*    serrano/prgm/project/hop/3.0.x/test/Makefile                     */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Fri Jan 20 13:46:40 2006                          */
#*    Last change :  Sun Jan  4 10:07:54 2015 (serrano)                */
#*    Copyright   :  2006-15 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    Example Makefile                                                 */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    Configuration                                                    */
#*---------------------------------------------------------------------*/
-include ../etc/Makefile.hopconfig
-include ../etc/Makefile.version

#*---------------------------------------------------------------------*/
#*    Population                                                       */
#*---------------------------------------------------------------------*/
POPULATION = Makefile \
  nodejs/BLACKLIST \
  nodejs/README \
  nodejs/TEST.in \
  nodejs/HOP.exe.in \
  nodejs/log \
  test262/BLACKLIST \
  test262/README \
  test262/TEST \
  hopjs/README \
  hopjs/TEST \
  hopjs/array.js \
  hopjs/ecma51.js \
  hopjs/number.js \
  hopjs/regexp.js \
  hopjs/unicode.js \
  hopjs/bufferrw.js \
  hopjs/json.js \
  hopjs/property.js \
  hopjs/string.js 
