#*=====================================================================*/
#*    serrano/prgm/project/hop/3.0.x/test/Makefile                     */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Fri Jan 20 13:46:40 2006                          */
#*    Last change :  Fri Dec 19 15:04:44 2014 (serrano)                */
#*    Copyright   :  2006-14 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    Example Makefile                                                 */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    Configuration                                                    */
#*---------------------------------------------------------------------*/
-include ../etc/Makefile.hopconfig
-include ../etc/Makefile.version

#*---------------------------------------------------------------------*/
#*    Population                                                       */
#*---------------------------------------------------------------------*/
POPULATION = Makefile \
  nodejs/BLACKLIST \
  nodejs/README \
  nodejs/TEST.in \
  nodejs/HOP.exe.in \
  nodejs/log \
  test262/BLACKLIST \
  test262/README \
  test262/TEST
