<CallExpression> --> ... | <HtmlExpression> | <TagExpression>

<HtmlExpression> -->
  | < <Tag> <TagAttributes> > <HtmlChildren> </ <Tag> >
  | < <Tag> />

<TagExpression> -->
    < <Tag> > { <TagArguments> }
  | < <Tag> > { <TagArguments> } </ <Tag> >

<Tag> --> 
    <Identifier>
  | <Identifier> . <Tag>

<TagAttributes> -->
  | <TagName>
  | <TagName> = <TagValue>

<TagName> --> [^ =]+

<TagValue> --> " [^"]* "
  | <~-Expression>
  | <$-Expression>

<HtmlChildren> -->
    <string>
  | <boolean>
  | <number>
  | <date>
  | <$-Expression>
  | <~-Expression>
  | <HtmlExpression>

<TagArguments> -->
  | <TagProperties>
  | <TagElements>
  | <TagProperties> , <TagElements>

<TagProperties> -->
  | <TagProperty>
  | <TagProperty> , <TagProperties>

<TagProperty> --> 
    <PropertyName> : <AssignmentExpression>

<TagElements> -->
  | <Expression>
  | <Expression> , <TagElements>  
