#*=====================================================================*/
#*    serrano/prgm/project/hop/2.4.x/arch/archlinux/Makefile           */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Sun Feb  7 07:41:50 2010                          */
#*    Last change :  Sun Feb 10 13:22:12 2013 (serrano)                */
#*    Copyright   :  2010-13 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    The Makefile that handles ARCHLINUX specific files               */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    Configuration                                                    */
#*---------------------------------------------------------------------*/
-include ../../etc/Makefile.hopconfig
-include ../../etc/Makefile.version

#*---------------------------------------------------------------------*/
#*    Variables                                                        */
#*---------------------------------------------------------------------*/
POPULATION = Makefile PKGBUILD.in hop.install rc.d/hop.in \
  conf.d/hop.in systemd/hop.service.in systemd/hop.socket.in sbin/hop

