;; ==========================================================
;; Class accessors
;; Bigloo (3.7b)
;; Inria -- Sophia Antipolis     Thu Nov 10 17:26:58 CET 2011 
;; (bigloo wiki_syntax.scm -classgen)
;; ==========================================================

;; The directives
(directives
   (cond-expand ((and bigloo-class-sans (not bigloo-class-generate))

;; wiki-syntax
(static
  (inline wiki-syntax?::bool ::obj)
  (inline make-wiki-syntax::wiki-syntax section12129::procedure section22130::procedure section32131::procedure section42132::procedure section52133::procedure h12134::procedure h22135::procedure h32136::procedure h42137::procedure h52138::procedure hr2139::procedure p2140::procedure ol2141::procedure ul2142::procedure li2143::procedure b2144::procedure em2145::procedure u2146::procedure del2147::procedure sub2148::procedure sup2149::procedure q2150::procedure tt2151::procedure code2152::procedure strike2153::procedure math2154::procedure note2155::procedure pre2156::procedure table2157::procedure tr2158::procedure th2159::procedure td2160::procedure href2161::procedure keyword2162::procedure type2163::procedure hyphen2164::procedure plugins2165::procedure verbatims2166::procedure prehook2167::procedure posthook2168::procedure)
  (inline wiki-syntax-posthook::procedure ::wiki-syntax)
  (inline wiki-syntax-posthook-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-prehook::procedure ::wiki-syntax)
  (inline wiki-syntax-prehook-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-verbatims::procedure ::wiki-syntax)
  (inline wiki-syntax-verbatims-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-plugins::procedure ::wiki-syntax)
  (inline wiki-syntax-plugins-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-hyphen::procedure ::wiki-syntax)
  (inline wiki-syntax-hyphen-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-type::procedure ::wiki-syntax)
  (inline wiki-syntax-type-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-keyword::procedure ::wiki-syntax)
  (inline wiki-syntax-keyword-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-href::procedure ::wiki-syntax)
  (inline wiki-syntax-href-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-td::procedure ::wiki-syntax)
  (inline wiki-syntax-td-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-th::procedure ::wiki-syntax)
  (inline wiki-syntax-th-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-tr::procedure ::wiki-syntax)
  (inline wiki-syntax-tr-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-table::procedure ::wiki-syntax)
  (inline wiki-syntax-table-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-pre::procedure ::wiki-syntax)
  (inline wiki-syntax-pre-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-note::procedure ::wiki-syntax)
  (inline wiki-syntax-note-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-math::procedure ::wiki-syntax)
  (inline wiki-syntax-math-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-strike::procedure ::wiki-syntax)
  (inline wiki-syntax-strike-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-code::procedure ::wiki-syntax)
  (inline wiki-syntax-code-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-tt::procedure ::wiki-syntax)
  (inline wiki-syntax-tt-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-q::procedure ::wiki-syntax)
  (inline wiki-syntax-q-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-sup::procedure ::wiki-syntax)
  (inline wiki-syntax-sup-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-sub::procedure ::wiki-syntax)
  (inline wiki-syntax-sub-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-del::procedure ::wiki-syntax)
  (inline wiki-syntax-del-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-u::procedure ::wiki-syntax)
  (inline wiki-syntax-u-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-em::procedure ::wiki-syntax)
  (inline wiki-syntax-em-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-b::procedure ::wiki-syntax)
  (inline wiki-syntax-b-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-li::procedure ::wiki-syntax)
  (inline wiki-syntax-li-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-ul::procedure ::wiki-syntax)
  (inline wiki-syntax-ul-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-ol::procedure ::wiki-syntax)
  (inline wiki-syntax-ol-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-p::procedure ::wiki-syntax)
  (inline wiki-syntax-p-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-hr::procedure ::wiki-syntax)
  (inline wiki-syntax-hr-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-h5::procedure ::wiki-syntax)
  (inline wiki-syntax-h5-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-h4::procedure ::wiki-syntax)
  (inline wiki-syntax-h4-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-h3::procedure ::wiki-syntax)
  (inline wiki-syntax-h3-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-h2::procedure ::wiki-syntax)
  (inline wiki-syntax-h2-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-h1::procedure ::wiki-syntax)
  (inline wiki-syntax-h1-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-section5::procedure ::wiki-syntax)
  (inline wiki-syntax-section5-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-section4::procedure ::wiki-syntax)
  (inline wiki-syntax-section4-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-section3::procedure ::wiki-syntax)
  (inline wiki-syntax-section3-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-section2::procedure ::wiki-syntax)
  (inline wiki-syntax-section2-set! ::wiki-syntax ::procedure)
  (inline wiki-syntax-section1::procedure ::wiki-syntax)
  (inline wiki-syntax-section1-set! ::wiki-syntax ::procedure)
)
)))

;; The definitions
(cond-expand ((and bigloo-class-sans (not bigloo-class-generate));; wiki-syntax
(define-inline (wiki-syntax?::bool obj::obj) ((@ isa? __object) obj (@ wiki-syntax __hop_wiki-syntax)))
(define-inline (make-wiki-syntax::wiki-syntax section12129::procedure section22130::procedure section32131::procedure section42132::procedure section52133::procedure h12134::procedure h22135::procedure h32136::procedure h42137::procedure h52138::procedure hr2139::procedure p2140::procedure ol2141::procedure ul2142::procedure li2143::procedure b2144::procedure em2145::procedure u2146::procedure del2147::procedure sub2148::procedure sup2149::procedure q2150::procedure tt2151::procedure code2152::procedure strike2153::procedure math2154::procedure note2155::procedure pre2156::procedure table2157::procedure tr2158::procedure th2159::procedure td2160::procedure href2161::procedure keyword2162::procedure type2163::procedure hyphen2164::procedure plugins2165::procedure verbatims2166::procedure prehook2167::procedure posthook2168::procedure) (instantiate::wiki-syntax (section1 section12129) (section2 section22130) (section3 section32131) (section4 section42132) (section5 section52133) (h1 h12134) (h2 h22135) (h3 h32136) (h4 h42137) (h5 h52138) (hr hr2139) (p p2140) (ol ol2141) (ul ul2142) (li li2143) (b b2144) (em em2145) (u u2146) (del del2147) (sub sub2148) (sup sup2149) (q q2150) (tt tt2151) (code code2152) (strike strike2153) (math math2154) (note note2155) (pre pre2156) (table table2157) (tr tr2158) (th th2159) (td td2160) (href href2161) (keyword keyword2162) (type type2163) (hyphen hyphen2164) (plugins plugins2165) (verbatims verbatims2166) (prehook prehook2167) (posthook posthook2168)))

(define-inline (wiki-syntax-posthook::procedure o::wiki-syntax) (with-access::wiki-syntax o (posthook) posthook))
(define-inline (wiki-syntax-posthook-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (posthook) (set! posthook v)))
(define-inline (wiki-syntax-prehook::procedure o::wiki-syntax) (with-access::wiki-syntax o (prehook) prehook))
(define-inline (wiki-syntax-prehook-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (prehook) (set! prehook v)))
(define-inline (wiki-syntax-verbatims::procedure o::wiki-syntax) (with-access::wiki-syntax o (verbatims) verbatims))
(define-inline (wiki-syntax-verbatims-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (verbatims) (set! verbatims v)))
(define-inline (wiki-syntax-plugins::procedure o::wiki-syntax) (with-access::wiki-syntax o (plugins) plugins))
(define-inline (wiki-syntax-plugins-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (plugins) (set! plugins v)))
(define-inline (wiki-syntax-hyphen::procedure o::wiki-syntax) (with-access::wiki-syntax o (hyphen) hyphen))
(define-inline (wiki-syntax-hyphen-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (hyphen) (set! hyphen v)))
(define-inline (wiki-syntax-type::procedure o::wiki-syntax) (with-access::wiki-syntax o (type) type))
(define-inline (wiki-syntax-type-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (type) (set! type v)))
(define-inline (wiki-syntax-keyword::procedure o::wiki-syntax) (with-access::wiki-syntax o (keyword) keyword))
(define-inline (wiki-syntax-keyword-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (keyword) (set! keyword v)))
(define-inline (wiki-syntax-href::procedure o::wiki-syntax) (with-access::wiki-syntax o (href) href))
(define-inline (wiki-syntax-href-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (href) (set! href v)))
(define-inline (wiki-syntax-td::procedure o::wiki-syntax) (with-access::wiki-syntax o (td) td))
(define-inline (wiki-syntax-td-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (td) (set! td v)))
(define-inline (wiki-syntax-th::procedure o::wiki-syntax) (with-access::wiki-syntax o (th) th))
(define-inline (wiki-syntax-th-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (th) (set! th v)))
(define-inline (wiki-syntax-tr::procedure o::wiki-syntax) (with-access::wiki-syntax o (tr) tr))
(define-inline (wiki-syntax-tr-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (tr) (set! tr v)))
(define-inline (wiki-syntax-table::procedure o::wiki-syntax) (with-access::wiki-syntax o (table) table))
(define-inline (wiki-syntax-table-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (table) (set! table v)))
(define-inline (wiki-syntax-pre::procedure o::wiki-syntax) (with-access::wiki-syntax o (pre) pre))
(define-inline (wiki-syntax-pre-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (pre) (set! pre v)))
(define-inline (wiki-syntax-note::procedure o::wiki-syntax) (with-access::wiki-syntax o (note) note))
(define-inline (wiki-syntax-note-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (note) (set! note v)))
(define-inline (wiki-syntax-math::procedure o::wiki-syntax) (with-access::wiki-syntax o (math) math))
(define-inline (wiki-syntax-math-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (math) (set! math v)))
(define-inline (wiki-syntax-strike::procedure o::wiki-syntax) (with-access::wiki-syntax o (strike) strike))
(define-inline (wiki-syntax-strike-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (strike) (set! strike v)))
(define-inline (wiki-syntax-code::procedure o::wiki-syntax) (with-access::wiki-syntax o (code) code))
(define-inline (wiki-syntax-code-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (code) (set! code v)))
(define-inline (wiki-syntax-tt::procedure o::wiki-syntax) (with-access::wiki-syntax o (tt) tt))
(define-inline (wiki-syntax-tt-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (tt) (set! tt v)))
(define-inline (wiki-syntax-q::procedure o::wiki-syntax) (with-access::wiki-syntax o (q) q))
(define-inline (wiki-syntax-q-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (q) (set! q v)))
(define-inline (wiki-syntax-sup::procedure o::wiki-syntax) (with-access::wiki-syntax o (sup) sup))
(define-inline (wiki-syntax-sup-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (sup) (set! sup v)))
(define-inline (wiki-syntax-sub::procedure o::wiki-syntax) (with-access::wiki-syntax o (sub) sub))
(define-inline (wiki-syntax-sub-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (sub) (set! sub v)))
(define-inline (wiki-syntax-del::procedure o::wiki-syntax) (with-access::wiki-syntax o (del) del))
(define-inline (wiki-syntax-del-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (del) (set! del v)))
(define-inline (wiki-syntax-u::procedure o::wiki-syntax) (with-access::wiki-syntax o (u) u))
(define-inline (wiki-syntax-u-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (u) (set! u v)))
(define-inline (wiki-syntax-em::procedure o::wiki-syntax) (with-access::wiki-syntax o (em) em))
(define-inline (wiki-syntax-em-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (em) (set! em v)))
(define-inline (wiki-syntax-b::procedure o::wiki-syntax) (with-access::wiki-syntax o (b) b))
(define-inline (wiki-syntax-b-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (b) (set! b v)))
(define-inline (wiki-syntax-li::procedure o::wiki-syntax) (with-access::wiki-syntax o (li) li))
(define-inline (wiki-syntax-li-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (li) (set! li v)))
(define-inline (wiki-syntax-ul::procedure o::wiki-syntax) (with-access::wiki-syntax o (ul) ul))
(define-inline (wiki-syntax-ul-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (ul) (set! ul v)))
(define-inline (wiki-syntax-ol::procedure o::wiki-syntax) (with-access::wiki-syntax o (ol) ol))
(define-inline (wiki-syntax-ol-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (ol) (set! ol v)))
(define-inline (wiki-syntax-p::procedure o::wiki-syntax) (with-access::wiki-syntax o (p) p))
(define-inline (wiki-syntax-p-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (p) (set! p v)))
(define-inline (wiki-syntax-hr::procedure o::wiki-syntax) (with-access::wiki-syntax o (hr) hr))
(define-inline (wiki-syntax-hr-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (hr) (set! hr v)))
(define-inline (wiki-syntax-h5::procedure o::wiki-syntax) (with-access::wiki-syntax o (h5) h5))
(define-inline (wiki-syntax-h5-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (h5) (set! h5 v)))
(define-inline (wiki-syntax-h4::procedure o::wiki-syntax) (with-access::wiki-syntax o (h4) h4))
(define-inline (wiki-syntax-h4-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (h4) (set! h4 v)))
(define-inline (wiki-syntax-h3::procedure o::wiki-syntax) (with-access::wiki-syntax o (h3) h3))
(define-inline (wiki-syntax-h3-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (h3) (set! h3 v)))
(define-inline (wiki-syntax-h2::procedure o::wiki-syntax) (with-access::wiki-syntax o (h2) h2))
(define-inline (wiki-syntax-h2-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (h2) (set! h2 v)))
(define-inline (wiki-syntax-h1::procedure o::wiki-syntax) (with-access::wiki-syntax o (h1) h1))
(define-inline (wiki-syntax-h1-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (h1) (set! h1 v)))
(define-inline (wiki-syntax-section5::procedure o::wiki-syntax) (with-access::wiki-syntax o (section5) section5))
(define-inline (wiki-syntax-section5-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (section5) (set! section5 v)))
(define-inline (wiki-syntax-section4::procedure o::wiki-syntax) (with-access::wiki-syntax o (section4) section4))
(define-inline (wiki-syntax-section4-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (section4) (set! section4 v)))
(define-inline (wiki-syntax-section3::procedure o::wiki-syntax) (with-access::wiki-syntax o (section3) section3))
(define-inline (wiki-syntax-section3-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (section3) (set! section3 v)))
(define-inline (wiki-syntax-section2::procedure o::wiki-syntax) (with-access::wiki-syntax o (section2) section2))
(define-inline (wiki-syntax-section2-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (section2) (set! section2 v)))
(define-inline (wiki-syntax-section1::procedure o::wiki-syntax) (with-access::wiki-syntax o (section1) section1))
(define-inline (wiki-syntax-section1-set! o::wiki-syntax v::procedure) (with-access::wiki-syntax o (section1) (set! section1 v)))

))
