;*=====================================================================*/
;*    serrano/prgm/project/hop/hopscheme/hop-aliases.scm               */
;*    -------------------------------------------------------------    */
;*    Author      :  Manuel Serrano                                    */
;*    Creation    :  Tue Apr 25 14:33:37 2006                          */
;*    Last change :  Mon May 28 14:03:29 2007 (serrano)                */
;*    Copyright   :  2006-07 Manuel Serrano                            */
;*    -------------------------------------------------------------    */
;*    HOP aliases.                                                     */
;*=====================================================================*/

;*---------------------------------------------------------------------*/
;*    The module                                                       */
;*---------------------------------------------------------------------*/
(module hopscheme_aliases
   (export (hopscheme-aliases)))

;*---------------------------------------------------------------------*/
;*    hopscheme-aliases ...                                            */
;*---------------------------------------------------------------------*/
(define (hopscheme-aliases)
   *hop-aliases*)

;*---------------------------------------------------------------------*/
;*    *hop-aliases* ...                                                */
;*---------------------------------------------------------------------*/
(define *hop-aliases*
   '((with-hop with_hop)
     (with-hop-call/cc with_hop_callcc)
     (timeout-start hop_timeout)
     (timeout-clear! hop_clear_timeout)
     (timeout-reset! hop_timeout_reset)
     (tooltip-hide hop_tooltip_hide)
     (tooltip-show hop_tooltip_show)
     (base64-encode base64_encode)
     (base64-decode base64_decode)
     (slider-value hop_slider_value_get)
     (slider-value-set! hop_slider_value_set)
     (slider-onchange hop_slider_onchange_get)
     (slider-onchange-set! hop_slider_onchange_set)
     (notepad-select hop_notepad_select)
     (iwindow-open hop_iwindow_open)
     (iwindow-close hop_iwindow_close)
     (window-open hop_window_open)
     (window-close hop_window_close)
     (paned-fraction hop_paned_fraction_get)
     (paned-fraction-set! hop_paned_fraction_set)
     (paned-onresize hop_paned_onresize_get)
     (paned-onresize-set! hop_paned_onresize_set)
     (tree-open hop_tree_open)
     (tree-close hop_tree_close)
     (tree-toggle hop_tree_toggle)
     (tree-reset! hop_tree_reset)
     (tree-selection hop_tree_selection)
     (hop-fx-repeat hop_fx_repeat)
     (hop-fx-fade-background hop_fx_fade_background)
     (dom-has-attributes? dom_has_attributes)
     (dom-get-attributes dom_get_attributes)
     (dom-has-attribute? dom_has_attribute)
     (dom-get-attribute dom_get_attribute)
     (dom-remove-attribute! dom_remove_attribute)
     (dom-set-attribute! dom_set_attribute)
     (dom-owner-document dom_owner_document)
     (dom-has-child-nodes? dom_has_child_nodes)
     (dom-child-nodes dom_child_nodes)
     (dom-first-child dom_first_child)
     (dom-last-child dom_last_child)
     (dom-next-sibling dom_next_sibling)
     (dom-previous-sibling dom_previous_sibling)
     (dom-node-name dom_node_name)
     (dom-node-type dom_node_type)
     (dom-parent-node dom_parent_node)
     (dom-append-child! dom_append_child)
     (dom-remove-child! dom_remove_child)
     (dom-clone-node dom_clone_node)
     (dom-insert-before! dom_insert_before)
     (dom-replace-child! dom_replace_child)
     (dom-get-element-by-id dom_get_element_by_id)
     (dom-get-elements-by-tag-name dom_get_elements_by_tag_name)
     (dom-get-elements-by-class dom_get_elements_by_class)
     (dom-node-eval hop_node_eval)
     (dom-set-child-node! dom_set_child_node)
     (node-style-get node_style_get)
     (node-style-set! node_style_set)
     (node-absolute-x hop_element_x)
     (node-absolute-y hop_element_y)
     (innerHTML-set! hop_innerHTML_set)
     (<A> dom_create_a)
     (<ABBR> dom_create_abbr)
     (<ACRONYM> dom_create_acronym)
     (<APPLET> dom_create_applet)
     (<AREA> dom_create_area)
     (<B> dom_create_b)
     (<BASE> dom_create_base)
     (<BASEFONT> dom_create_basefont)
     (<BDO> dom_create_bdo)
     (<BIG> dom_create_big)
     (<BLOCKQUOTE> dom_create_blockquote)
     (<BODY> dom_create_body)
     (<BR> dom_create_br)
     (<BUTTON> dom_create_button)
     (<CANVAS> dom_create_canvas)
     (<CAPTION> dom_create_caption)
     (<CENTER> dom_create_center)
     (<CITE> dom_create_cite)
     (<CODE> dom_create_code)
     (<COL> dom_create_col)
     (<COLGROUP> dom_create_colgroup)
     (<DD> dom_create_dd)
     (<DEL> dom_create_del)
     (<DFN> dom_create_dfn)
     (<DIR> dom_create_dir)
     (<DIV> dom_create_div)
     (<DL> dom_create_dl)
     (<DT> dom_create_dt)
     (<EM> dom_create_em)
     (<FIELDSET> dom_create_fieldset)
     (<FONT> dom_create_font)
     (<FORM> dom_create_form)
     (<FRAME> dom_create_frame)
     (<FRAMESET> dom_create_frameset)
     (<H1> dom_create_h1)
     (<H2> dom_create_h2)
     (<H3> dom_create_h3)
     (<H4> dom_create_h4)
     (<H5> dom_create_h5)
     (<H6> dom_create_h6)
     (<HR> dom_create_hr)
     (<HTML> dom_create_html)
     (<I> dom_create_i)
     (<IFRAME> dom_create_iframe)
     (<INPUT> dom_create_input)
     (<INS> dom_create_ins)
     (<ISINDEX> dom_create_isindex)
     (<KBD> dom_create_kbd)
     (<LABEL> dom_create_label)
     (<LEGEND> dom_create_legend)
     (<LI> dom_create_li)
     (<LINK> dom_create_link)
     (<MAP> dom_create_map)
     (<MARQUEE> dom_create_marquee)
     (<MENU> dom_create_menu)
     (<META> dom_create_meta)
     (<NOFRAMES> dom_create_noframes)
     (<NOSCRIPT> dom_create_noscript)
     (<OBJECT> dom_create_object)
     (<OL> dom_create_ol)
     (<OPTGROUP> dom_create_optgroup)
     (<OPTION> dom_create_option)
     (<P> dom_create_p)
     (<PARAM> dom_create_param)
     (<PRE> dom_create_pre)
     (<Q> dom_create_q)
     (<S> dom_create_s)
     (<SAMP> dom_create_samp)
     (<SCRIPT> dom_create_script)
     (<SELECT> dom_create_select)
     (<SMALL> dom_create_small)
     (<SPAN> dom_create_span)
     (<STRIKE> dom_create_strike)
     (<STRONG> dom_create_strong)
     (<STYLE> dom_create_style)
     (<SUB> dom_create_sub)
     (<SUP> dom_create_sup)
     (<TABLE> dom_create_table)
     (<TBODY> dom_create_tbody)
     (<TD> dom_create_td)
     (<TEXTAREA> dom_create_textarea)
     (<TFOOT> dom_create_tfoot)
     (<TH> dom_create_th)
     (<THEAD> dom_create_thead)
     (<TITLE> dom_create_title)
     (<TR> dom_create_tr)
     (<TT> dom_create_tt)
     (<U> dom_create_u)
     (<UL> dom_create_ul)
     (<VAR> dom_create_var)
     (<IMG> dom_create_img)
     (<HEAD> dom_create_head)
     (<DELAY> dom_create_delay)
     (<INLINE> dom_create_inline)
     (<NOTEPAD> dom_create_notepad)
     (<NPHEAD> dom_create_nphead)
     (<NPTAB> dom_create_nptab)
     (<NPTABHEAD> dom_create_nptabhead)
     (<PAN> dom_create_pan)
     (<PANED> dom_create_paned)
     (<SLIDER> dom_create_slider)
     (<SORTTABLE> dom_create_sorttable)
     (cookie-remove! hop_cookie_remove)
     (cookie-get hop_cookie_get_value)
     (cookie-set! hop_cookie_set_value)
     (request-get hop_request_get)
     (request-set! hop_request_set)
     (debug hop_debug)
     (debug-reset! hop_debug_reset)
     (hop-load hop_load)
     (add-window-onload! hop_window_onload_add)
     (add-window-onunload! hop_window_onunload_add)
     (add-event-listener! hop_add_event_listener)
     (remove-event-listener! hop_remove_event_listener)
     (stop-event-propagation hop_stop_propagation)
     (event-mouse-x hop_event_mouse_x)
     (event-mouse-y hop_event_mouse_y)
     (event-key-code hop_event_key_code)
     (html-element? hop_is_html_element)
     (make-history hop_make_history)
     (history-add! hop_history_add)
     (with-history hop_with_history)
     (find-runtime-type hop_find_runtime_type)))
