# This file exists because the possibility of releasing scheme2js separately

#*---------------------------------------------------------------------*/
#*    Standard Bigloo configuration                                    */
#*---------------------------------------------------------------------*/
-include ../etc/Makefile.hopconfig
-include ../etc/Makefile.version
-include $(BIGLOOLIBDIR)/Makefile.config

#*---------------------------------------------------------------------*/
#*    Compilers, Tools and Destinations                                */
#*---------------------------------------------------------------------*/
HOPCLOSELIBS_S	= $(BGLCLOSELIBS_S)
HOPCLOSELIBS_U	= $(BGLCLOSELIBS_U)
HOPCLOSELIBS_ES	= $(BGLCLOSELIBS_ES)
HOPCLOSELIBS_EU	= $(BGLCLOSELIBS_EU)

SCHEME2JSSHAREDIR = $(HOPSHAREDIR)
