#*=====================================================================*/
#*    .../hop/arch/android/hzdemo/arch/android/Makefile.config.in      */
#*    -------------------------------------------------------------    */
#*    Author      :  manuel serrano                                    */
#*    Creation    :  Thu May 14 11:45:19 2020                          */
#*    Last change :  Fri Nov 13 15:29:30 2020 (serrano)                */
#*    Copyright   :  2020 manuel serrano                               */
#*    -------------------------------------------------------------    */
#*    Android Make configuration                                       */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    Hop configuration                                                */
#*---------------------------------------------------------------------*/
HOPAPP = hzdemo
HOPAPKVERSION = 0.0.0

HOPAPKNAME = $(HOPAPP)-$(HOPAPKVERSION)
HOPHZ = $(HOPAPKNAME).hz

HOPDIR = /home/serrano/prgm/project/hop/hop

ANDROIDWEBLET = /home/serrano/prgm/project/hop/hop/arch/android/hzdemo

ANDROIDMANIFEST = $(ANDROIDWEBLET)/arch/android/AndroidManifest.xml
ANDROIDRES = $(ANDROIDWEBLET)/arch/android/res

ANDROIDHOPDEBUGLEVEL = -g0

