#*=====================================================================*/
#*    serrano/prgm/project/hop/3.2.x/docker/Makefile                   */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Fri Jan 20 13:46:40 2006                          */
#*    Last change :  Fri May  4 10:28:50 2018 (serrano)                */
#*    Copyright   :  2006-18 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    ETC Makefile                                                     */
#*=====================================================================*/
do: 

#*---------------------------------------------------------------------*/
#*    Configuration                                                    */
#*---------------------------------------------------------------------*/
-include ../etc/Makefile.hopconfig
-include ../etc/Makefile.version

POPULATION=Makefile Dockerfile hop.docker hoprc.hop README.md
