#*=====================================================================*/
#*    serrano/prgm/project/hop/3.0.x/examples/Makefile                 */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Fri Jan 20 13:46:40 2006                          */
#*    Last change :  Mon Nov 24 17:55:20 2014 (serrano)                */
#*    Copyright   :  2006-14 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    Example Makefile                                                 */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    Configuration                                                    */
#*---------------------------------------------------------------------*/
-include ../etc/Makefile.hopconfig
-include ../etc/Makefile.version

#*---------------------------------------------------------------------*/
#*    Population                                                       */
#*---------------------------------------------------------------------*/
POPULATION = Makefile \
  async/async.js \
  arraybuffer/arraybuffer.js \
  require/node_modules require/node_modules/mod2.js require/require.js \
  require/mod1.js \
  requirec/requirec.js requirec/mod2.js requirec/mod1.js \
  requirew/requirew.js requirew/provider.js requirew/foo.js \
  js2http/js2http.js js2http/fact.js \
  arraybuffer/arraybuffer.js \
  qunit/qunit.js \
  event/event.js \
  fs/fs.js \
  url/url.js \
  file/file.js \
  websocket/wsserver.js websocket/wsclient.js \
  wsclient/wsclient.js \
  svc/svc.js \
  svc2/svc2.js svc2/extern.js \
  svc3/svc3.js \
  svc4/svc4.js \
  html/html.js html/html.hss \
  hss/hss.hss hss/hss.js \
  tree/tree.js \
  tower/tower.js \
  dom/dom.js \
  jquery/jquery.js \
  hello/hello.js \
  debug/debug.js debug/bugs.js \
  proxy/proxy.js \
  worker/slave.js worker/worker.js worker/bar.js \
  worker2/slave.js worker2/worker2.js \
  worker3/slave.js worker3/worker3.js worker3/bar.js \
  worker4/slave.js worker4/worker4.js \
  sqlite/db.sqlite sqlite/sqlite.js sqlite/sqlite_core.js \
  widget/node_modules \
  widget/node_modules/flipcounter \
  widget/node_modules/flipcounter/lib \
  widget/node_modules/flipcounter/lib/flipcounter.js \
  widget/node_modules/flipcounter/client \
  widget/node_modules/flipcounter/client/flipcounter.min.js \
  widget/node_modules/flipcounter/package.json \
  widget/node_modules/flipcounter/hss \
  widget/node_modules/flipcounter/hss/flipcounter.hss \
  widget/node_modules/flipcounter/etc \
  widget/node_modules/flipcounter/etc/img \
  widget/node_modules/flipcounter/etc/img/digits-transparent.png \
  widget/node_modules/flipcounter/etc/img/digits.png \
  widget/node_modules/flipcounter-1.0.0.tgz \
  widget/widget.js \
  keepalive/keepalive.js keepalive/keepalive.hss \
  authentication/authentication.js \
  image/image.js \
  pair/pair.js \
  hzdemo/hzdemo.js \
  hzdemo/README \
  hzdemo/foo/package.json \
  hzdemo/foo/foo.js \
  hzdemo/foo/foo.hss \
  hzdemo/foo/etc \
  hzdemo/foo/etc/favicon.png \
  hzdemo/foo/etc/logo.png \
  hzdemo/foo-1.0.0.hz \
  scheme/scheme.js \
  scheme/scheme.hop


#*---------------------------------------------------------------------*/
#*    install                                                          */
#*---------------------------------------------------------------------*/
install:

#*---------------------------------------------------------------------*/
#*    uninstall                                                        */
#*---------------------------------------------------------------------*/
uninstall:

#*---------------------------------------------------------------------*/
#*    clean                                                            */
#*---------------------------------------------------------------------*/
clean:

#*---------------------------------------------------------------------*/
#*    devclean                                                         */
#*---------------------------------------------------------------------*/
devclean: clean

