#*=====================================================================*/
#*    serrano/prgm/project/hop/2.3.x/arch/Makefile                     */
#*    -------------------------------------------------------------    */
#*    Author      :  Manuel Serrano                                    */
#*    Creation    :  Fri Jan 20 13:46:40 2006                          */
#*    Last change :  Wed May 23 17:09:43 2012 (serrano)                */
#*    Copyright   :  2006-12 Manuel Serrano                            */
#*    -------------------------------------------------------------    */
#*    ETC Makefile                                                     */
#*=====================================================================*/

#*---------------------------------------------------------------------*/
#*    Configuration                                                    */
#*---------------------------------------------------------------------*/
-include ../etc/Makefile.hopconfig
-include ../etc/Makefile.version

#*---------------------------------------------------------------------*/
#*    Population                                                       */
#*---------------------------------------------------------------------*/
POPULATION = Makefile

POPDIRS = felix android macosx vm # debian archlinux vm

install:

uninstall:

clean:

devclean: clean

