#!/bin/bash

rest=
verb=-v
basedir=$pwd
hop=../../bin/hop

while : ; do

  case $1 in
    "")
     break;;

  -h|--help)
    echo "usage: $0 [-v|-s] [--basedir dir] [--hop hop]";
    echo "example: $0";
    exit 0;;

  -v)
    verb="$verb -v";;

  -s)
    verb="";;

  -*)
    rest=$1;;

  --basedir)
    shift;
    basedir=$1;;    

  --hop)
    shift;
    hop=$1;;    

  esac

  shift
done   

success=0
failure=0
i=0

for path in *.js; do
  i=`expr $i + 1`

  echo -n "$i. $path ... "
  $hop -g --no-zeroconf --no-server $path > /tmp/TEST-HOPJS.out 2>&1

  if [ $? = 0 ]; then
    echo "ok.";
    success=`expr $success + 1`
  else
    echo "failure !!!"
    if [ "$verb " != " " ]; then
      cat /tmp/TEST-HOPJS.out
    fi
    failure=`expr $failure + 1`
  fi
  /bin/rm -f /tmp/TEST-HOPJS.out
done

echo "`expr $success + $failure` executed"
echo "   $success success"
echo "   $failure failure"
