#!/bin/bash

rest=
verb=
basedir=$pwd
hop=../../bin/hop

while : ; do

  case $1 in
    "")
     break;;

  -h|--help)
    echo "usage: $0 [-v|-s] [--basedir dir] [--hop hop]";
    echo "example: $0";
    exit 0;;

  -v)
    verb="$verb -v";;

  -v2)
    verb="$verb -v -v";;

  -s)
    verb="";;

  -*)
    rest=$1;;

  --basedir)
    shift;
    basedir=$1;;    

  --hop)
    shift;
    hop=$1;;    

  esac

  shift
done   

success=0
failure=0
i=0

run() {
  echo $1 | grep rc.js 2> /dev/null > /dev/null
  
  if [ $? != 0 ]; then
    i=`expr $i + 1`

    echo -n "$i. $path ... "
    if [ "$verb " != " " ]; then
      echo ""
      echo -n "$hop -g --no-zeroconf $* ..."
    fi
    $hop -g --no-zeroconf $* > /tmp/TEST-HOPJS.out 2>&1

    if [ $? = 0 ]; then
      echo "ok.";
      success=`expr $success + 1`
    else
      echo "failure !!!"
      if [ "$verb " != " " ]; then
        cat /tmp/TEST-HOPJS.out
      fi
      failure=`expr $failure + 1`
    fi
    /bin/rm -f /tmp/TEST-HOPJS.out
  fi
}

for path in noserv/*.js; do
   if [ -f $path.rc.js ]; then
     run $path --no-server --rc-file $path.rc.js
   else
     run $path -q --no-server
   fi
done

for path in serv/*.js; do
    if [ -f $path.rc.js ]; then
	if [ -f $path.args ]; then
	    run $path -p 0 `cat $path.args` --rc-file $path.rc.js
	else
	    run $path -p 0 --rc-file $path.rc.js
	fi
    else       
	if [ -f $path.args ]; then
	    run $path -p 0 `cat $path.args` --rc-file passwd.hop
	else
	    run $path -p 0 --rc-file passwd.hop
	fi
    fi
       
done

echo "`expr $success + $failure` executed"
echo "   $success success"
echo "   $failure failure"
