name: Hop CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt -qq update
      - run: sudo apt install -y dh-make
      - run: sudo apt install -y libssl3 libssl-dev
      - run: sudo apt install -y libsqlite3-0 libsqlite3-dev
      - run: sudo apt install -y libasound2-dev
      - run: sudo apt install -y libflac-dev
      - run: sudo apt install -y libmpg123-0 libmpg123-dev
      - run: sudo apt install -y libavahi-core7 libavahi-core-dev libavahi-common-dev libavahi-common3 libavahi-client3 libavahi-client-dev
      - run: sudo apt install -y libunistring-dev
      - run: sudo apt install -y libpulse-dev libpulse0
      - run: sudo apt install -y automake libtool
      - run: sudo apt install -y libgmp-dev libgmp3-dev libgmp10

      - run: wget -nv ftp://ftp-sop.inria.fr/indes/fp/Bigloo/bigloo-unstable.tar.gz -O /tmp/bigloo-unstable.tar.gz > /dev/null
      - run: (cd /tmp && tar xfz /tmp/bigloo-unstable.tar.gz)
      - run: (cd /tmp/bigloo-unstable && ./configure && make && sudo make install)

      - run: ./configure && make && sudo make install
      - run: (cd test/hopjs; ./TEST)

